spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.thymeleaf.cache=false

application.graphapi.user=user@example.com
application.graphapi.tenant=AZURE_TENANT_ID
application.graphapi.client_id=AZURE_API_CLIENT_ID
application.graphapi.client_secret=AZURE_API_CLIENT_SECRET

application.graphapi.auth_endpoint=https://login.microsoftonline.com/${application.graphapi.tenant}/oauth2/v2.0/token
application.graphapi.createMeeting_endpoint=https://graph.microsoft.com/v1.0/users/${application.graphapi.user}/onlineMeetings
